{% set name = "geocat-f2py" %}
{% set version = "2023.03.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://github.com/NCAR/{{ name }}/archive/v{{ version }}.tar.gz # For building from a specific tag's tarball
  sha256: a706d2ac8f623c0131e843ccc5d50b25bf065b7e5a453d74c1bca02bff434bb5
  # git_tag: v{{ version }}   # For building from a specific tag
  # git_rev: march # For building from main branch for debugging purposes
  # git_url: https://github.com/NCAR/{{ name }}.git

build:
  number: 1
  skip: true  # [py<38 or win]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - pip                                 # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
    - numpy >=1.22                        # [build_platform != target_platform]
    - {{ compiler('fortran') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - numpy >=1.22
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
  run:
    - python
    - numpy >=1.22
    - xarray
    - dask

test:
  requires:
    - pytest
  imports:
    - geocat
    - geocat.f2py
  commands:
    - pytest test
  source_files:
    - test

about:
  home: https://geocat.ucar.edu/
  summary: GeoCAT-f2py wraps, in Python, the compiled language implementations of some of the computational functions found under the GeoCAT-comp umbrella.
  dev_url: https://github.com/NCAR/{{ name }}
  doc_url: https://{{ name }}.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NCAR/geocat # GeoCAT https://github.com/orgs/NCAR/teams/geocat
    - anissa111 # A. Zacharias https://github.com/anissa111
    - erogluorhan # O. Eroglu https://github.com/erogluorhan
    - hCraker # H. Craker https://github.com/hCraker
    - pilotchute # A. Kootz https://github.com/pilotchute
